
package Views;

import Models.Clothing;
import Models.Customer;
import Models.DBHandler;
import Models.Footwear;
import Models.Order;
import Models.Orderline;
import Models.Product;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel russell 22/1/2019
 */
public class FrmCustomerViewBasket extends javax.swing.JFrame {

    //global attributes
    private Customer LoggedUser;
    private Order CustomerOrder;
    
    /**
     * Creates new form FrmCustomerViewBasket
     */
    
    //initalises privates attributes and GUI components, adds all products from customer order to basket display
    public FrmCustomerViewBasket(Customer Cu) {
        initComponents();
        
        LoggedUser = Cu;
        CustomerOrder = LoggedUser.findLatestOrder();
        
        DefaultTableModel basket = (DefaultTableModel) tblBasket.getModel();
        
        for(Map.Entry<Integer, Orderline> olEntry : CustomerOrder.getOrderLines().entrySet()){
         
            Orderline actualOrderLine = olEntry.getValue();
            
            if(actualOrderLine.getProduct().getClass().getName().equals("Models.Clothing"))
            {
                Clothing tempClothing = (Clothing) actualOrderLine.getProduct();
                basket.addRow(new Object[]{tempClothing.getProductID(),tempClothing.getProductName(),"£" + String.format("%.02f",tempClothing.getPrice()),tempClothing.getStockLevel(),tempClothing.getMeasurement(),0,actualOrderLine.getQuantity()});
            }
            else
            {
                Footwear tempFootwear = (Footwear) actualOrderLine.getProduct();
                basket.addRow(new Object[]{tempFootwear.getProductID(),tempFootwear.getProductName(),"£" + String.format("%.02f",tempFootwear.getPrice()),tempFootwear.getStockLevel(),0,tempFootwear.getSize(),actualOrderLine.getQuantity()});
            }
            
            
        }
        
        tblBasket.setModel(basket);
        lblTotalSum.setText("£" + String.format("%.02f",CustomerOrder.getOrderTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBasket = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        lblTotalSum = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblBasket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "ProductName", "Price", "Stock", "Measurment", "Size", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblBasket);

        btnRemove.setText("Remove Product");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnBuy.setText("Buy Products");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalSum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuy)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuy)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //navigates back to viewproduct form
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    FrmCustomerViewProduct newfrm = new FrmCustomerViewProduct(LoggedUser);
    this.dispose();
    newfrm.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    //updates order status to complete in database
    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        if(!CustomerOrder.getOrderLines().isEmpty())
        {
        CustomerOrder.setStatus("Complete");
        
        DBHandler DBH = new DBHandler();
        DBH.completeOrder(CustomerOrder.getOrderID());
        
        FrmCustomerConfirmation newFrm = new FrmCustomerConfirmation(LoggedUser);
        this.dispose();
        newFrm.setVisible(true);   
        }
        else
        {
        this.lblError.setText("Error: Please add a product to basket");
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    //removes product from order basket
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if(tblBasket.getSelectedRow() == -1)
        {
            this.lblError.setText("Error: Select A Product");
        }
        else
        {
            DefaultTableModel basketModel = (DefaultTableModel)tblBasket.getModel();
            int productid = Integer.parseInt(String.valueOf(basketModel.getValueAt(tblBasket.getSelectedRow(), 0))); 
            int quantity = Integer.parseInt(String.valueOf(basketModel.getValueAt(tblBasket.getSelectedRow(), 6)));
            
            //CustomerOrder.changeProductStockLevel(new Product(productid,quantity));
            
            CustomerOrder.removeOrderLine(productid);
            lblError.setText("Product Removed");
            
            DefaultTableModel basket = (DefaultTableModel)tblBasket.getModel();
            basket.removeRow(tblBasket.getSelectedRow());
            
            tblBasket.setModel(basket); 
            
            this.lblTotalSum.setText("£" + String.format("%.02f",CustomerOrder.getOrderTotal()));
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrmCustomerViewBasket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblTotalSum;
    private javax.swing.JTable tblBasket;
    // End of variables declaration//GEN-END:variables
}
